# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "664ef581318cd90cf7f220ed6561b4e1"
name = "c1"
handle = "c1-4"
application_url = "https://china-rug-jake-mr.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-014072ef.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://china-rug-jake-mr.trycloudflare.com/auth/callback",
  "https://china-rug-jake-mr.trycloudflare.com/auth/shopify/callback",
  "https://china-rug-jake-mr.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
